config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/about'
  get 'home/menus'
  get 'home/tour'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
    
    def about
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to image_tag("/app/assets/images/milliways_logo.png "), root_path, class:"navbar-brand" %>
        <img alt="Milliways" src="...">
      </a>
    </div>
  </div>
</nav>

<%= link_to 'Menus', home_menus_path %>
<%= link_to 'Tour', home_tour_path %>
<%= link_to 'About', home_about_path %>
<%= link_to 'Visit Us', home_tour_path %>

app/views/home/about.html.erb
about page

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Milliways: Restaurant at the End of the Universe</title>
  <link rel="shortcut icon" href="layouts/favicon.ico" type="image/x-icon">
  <link rel="icon" href="layouts/favicon.ico" type="image/x-icon"> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'home/header' %>

<%= yield %>

</body>
</html>